name: Prisma baseline — create-only migration and PR

on:
  workflow_dispatch:
    inputs:
      migration_name:
        description: 'Migration name (e.g. init)'
        required: true
        default: init
      db_authoritative:
        description: 'Run prisma db pull before creating migration? (true/false)'
        required: false
        default: 'false'

jobs:
  create-and-pr-open:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Optional: pull DB schema (if db_authoritative)
        if: ${{ inputs.db_authoritative == 'true' }}
        run: |
          echo "Running prisma db pull"
          npx prisma db pull
          npx prisma generate

      - name: Create migration (create-only)
        run: |
          echo "Creating migration: ${{ inputs.migration_name }}"
          npx prisma migrate dev --name "${{ inputs.migration_name }}" --create-only

      - name: Commit migration files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add prisma/migrations || true
          if git diff --staged --quiet; then
            echo "No migration files to commit"
          else
            git commit -m "chore(prisma): add baseline migration (${{ inputs.migration_name }}) [skip ci]" || true
          fi

      - name: Create Pull Request with migration
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(prisma): add baseline migration (${{ inputs.migration_name }}) [skip ci]"
          branch: "prisma/baseline-${{ github.run_id }}"
          title: "prisma: add baseline migration (${ { { inputs.migration_name } } })"
          body: |
            This PR contains a create-only Prisma migration generated by CI for review.

            Please review the SQL and schema changes in `prisma/migrations` and if they match the target DB, approve the PR. After merging, trigger the `prisma-resolve.yml` workflow (manual) against the target environment to mark the migration as applied.

            Steps:
            - Review migration SQL
            - Confirm no destructive changes
            - Merge PR into `main`

          labels: |-
            migration
