name: Prisma Baseline

on:
  push:
    branches: [ main ]
    paths:
      - 'prisma/schema.prisma'
      - 'prisma/migrations/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'prisma/schema.prisma'
      - 'prisma/migrations/**'

jobs:
  baseline:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Generate Prisma client
      run: npx prisma generate

    - name: Create baseline migration
      run: |
        npx prisma migrate dev --name baseline --create-only
        echo "Baseline migration created"

    - name: Validate schema
      run: npx prisma validate

    - name: Check migration status
      run: npx prisma migrate status

    - name: Comment on PR
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '🔄 **Prisma Baseline Check**\n\n✅ Schema validation passed\n✅ Migration files generated\n✅ Database compatibility verified\n\nReady for review and merge.'
          })
